# Generated by Django 4.2.28 on 2026-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HttpFetcherSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Friendly label for this source, e.g. "Daily Landscape Cam".', max_length=200)),
                ('url', models.URLField(help_text='Direct image URL. The server must return image bytes.', max_length=2000)),
                ('fetch_interval', models.CharField(choices=[('hourly', 'Hourly'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='daily', help_text='How often to fetch a new image from this URL.', max_length=20)),
                ('enabled', models.BooleanField(default=True)),
                ('last_fetched_at', models.DateTimeField(blank=True, help_text='Timestamp of the last successful fetch. Updated automatically.', null=True)),
            ],
            options={
                'verbose_name': 'HTTP Fetcher Source',
                'verbose_name_plural': 'HTTP Fetcher Sources',
            },
        ),
        migrations.CreateModel(
            name='TelegramSourceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_token', models.CharField(help_text='Telegram Bot API token.', max_length=200)),
                ('chat_id', models.CharField(help_text='Only updates from this chat/channel ID will be accepted.', max_length=100)),
                ('webhook_url', models.URLField(help_text='Public HTTPS URL registered with Telegram as the webhook endpoint.', max_length=500)),
                ('enabled', models.BooleanField(default=True, help_text='Disable to stop processing Telegram updates without deleting config.')),
            ],
            options={
                'verbose_name': 'Telegram Source',
                'verbose_name_plural': 'Telegram Source',
            },
        ),
    ]
