# Generated by Django 4.2.28 on 2026-02-21 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CleanupConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_folder_size_mb', models.PositiveIntegerField(default=500, help_text='Maximum total size of media/images/ in megabytes.')),
                ('cleanup_interval_seconds', models.PositiveIntegerField(default=3600, help_text='Informational only — actual schedule is set in cron/docker-compose.')),
            ],
            options={
                'verbose_name': 'Cleanup Configuration',
                'verbose_name_plural': 'Cleanup Configuration',
            },
        ),
        migrations.CreateModel(
            name='ScreensaverConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grid_fetch_interval_seconds', models.PositiveIntegerField(default=60, help_text='How often (seconds) the browser re-fetches the preview grid.')),
                ('slideshow_interval_seconds', models.PositiveIntegerField(default=5, help_text='How long (seconds) each image is displayed before advancing.')),
                ('transition', models.CharField(choices=[('burn', 'Burn'), ('fade', 'Fade'), ('slide', 'Slide'), ('zoom', 'Zoom')], default='burn', help_text="Transition effect used when transition_mode is 'fixed'.", max_length=20)),
                ('transition_mode', models.CharField(choices=[('fixed', 'Fixed — always use the selected transition'), ('random', 'Random — pick a different transition each slide')], default='random', max_length=20)),
            ],
            options={
                'verbose_name': 'Screensaver Configuration',
                'verbose_name_plural': 'Screensaver Configuration',
            },
        ),
    ]
